name: Deployment Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deployment-test:
    runs-on: ubuntu-22.04 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9" 

    - name: Install dependencies
      run: pip install requests

    - name: Run deployment test
      run: python Run.py
